language: ruby
sudo: false
env:
  matrix:
  - BROWSER=chromium EXT=zip
  - BROWSER=firefox EXT=xpi
script: ./tools/make-${BROWSER}.sh all
deploy:
  provider: releases
  api_key:
    secure: FknPhrs+Y3fXAhXiK9feaSvfHrfEoa4Gxv5iOu13JHaZN0RVmnbTAkx376LU786lEtuG1RJPumkMJ0Bc0U/sgy9dz3iWkwXtXTSa4BAvuJOQA4oeeDLXoHiy0b41VFMbMKUGlUaskW5X3Q7cxpHKEZrm5HRU+dO1jemTTSlI0P0=
  file: dist/build/uBlock.${BROWSER}.${EXT}
  skip_cleanup: true
  on:
    repo: fwalch/uBlock
    tags: true
    all_branches: true
