language: ruby
sudo: false
env:
  matrix:
  - BROWSER=chromium EXT=zip
  - BROWSER=firefox EXT=xpi
script: ./tools/make-${BROWSER}.sh all
deploy:
  provider: releases
  api_key:
    secure: aoUrSk4xrLG21zoYmguLG4GofniXYrlplmvhoJ5LNMXLmJfXG3K6DkbA2JO7Oodb25Z2qLgwm5kmAg8GdSfm7HGsni+S3Ih5lsD/kKdCqVx41cWWRN7rCfpeM/NwpndE5a4pvOm9zLhuWWbzBy7baNefSjVNTSgDx92RH2MepmM=
  file: dist/build/uBlock.${BROWSER}.${EXT}
  skip_cleanup: true
  on:
    repo: chrisaljoudi/uBlock
    tags: true
    all_branches: true
