[Adblock Plus 2.0]
! Title: Eesti saitidele kohandatud filter
! Homepage: https://adblock.ee
! Expires: 1 days
! Version: 20190805
! License: CC0 1.0 Universal http://creativecommons.org/publicdomain/zero/1.0/legalcode
##A[href*="http://pay4results24.eu"]
##iframe[src*="cherrystatic.net"]
##iframe[src*="date.elu24.ee"]
##IFRAME[src*="sale24.ee"]
##iframe[src*="static.chilli.ee"]
##iframe[src*="superdeal.ee"]
/js/ads.
/js/ads_
1182.ee###content-box-right
1a.ee##.ad-box
://ads.
://ads2.
@@ado.delfi.ee/files/js/ado.js
@@http://ads.postimees.ee/ads/list/*telecast*
@@http://ads.postimees.ee/crossdomain.xml
@@||autonet.ee/showads.js
@@||delfi.ee*/js/ads.
@@||delfi.ee^$generichide
@@||emediate.se$third-party,domain=tartupostimees.ee|postimees.ee
@@||fwmrm.net^$domain=tv3play.tv3.ee
@@||kinnistuportaal.rik.ee/KAEP/Media/img/logos/exchange_banner_idkaart.gif
@@||newrelic.com^$domain=tv3play.tv3.ee
@@||tv3play.tv3.ee/ad/banner/*
accelerista.com##.top-bar-content
accelerista.com##div[id^="bsa-block"]
ado.delfi.ee
aliexpress.com##.top-banner-container
aripaev.ee##div[class*="banner-placeholder"]
auto24.ee##DIV.adzones
auto24.ee##DIV[id*="_panels_kb_ad"]
auto24.ee,motors24.ee,mangukoobas.lahendus.ee##DIV.banner
biker.ee##.noscriptcssresponsive.noscriptcss.panel
cdn.playapi.mtgx.tv/*/banners/*
cherry.ee##a[href*=site_banner]
delfi.ee###ab-notify-ribbon
delfi.ee###ab-top-bar
delfi.ee###city24
delfi.ee###city24_precom
delfi.ee###cv-online-ad
delfi.ee###delfi-countdown
delfi.ee###delfiTopBar
delfi.ee###dh_middle
delfi.ee###local_offers
delfi.ee###pre_footer > div
delfi.ee###rlmm_banner
delfi.ee###tb-tv3_delfi
delfi.ee###tb-zave
delfi.ee##.articleCustomEnd > .c-cinema
delfi.ee##.articleRelated
delfi.ee##.aside
delfi.ee##.city24m-banner-container
delfi.ee##.cxense-news
delfi.ee##.dbrs-ab
delfi.ee##.flex.col-300.col:-abp-has(> .col-has-ad)
delfi.ee##.md-banner-container
delfi.ee##.row.row-space-around.ad-container
delfi.ee##.zave_r
delfi.ee##DIV.djoke
delfi.ee##DIV.eshops
delfi.ee##DIV.HdBnr
delfi.ee##DIV.s-ribbon
delfi.ee##DIV.tgames
delfi.ee##div[class$="col-has-ad"] div[id^="dwidget"]
delfi.ee##div[class$="col-has-ad"] table
delfi.ee##DIV[class$="fb_wall_bg"]
delfi.ee##div[class*="col-has-ad"]
delfi.ee##DIV[id$="_728"]
delfi.ee##div[id*="sliding"][style*="width: 192px"]
delfi.ee##div[id^="ab-notify-bar"]
delfi.ee##div[id^="kaup24-fade"]
delfi.ee##iframe[name^="rb_kaup24"]
delfi.ee#$#.article__body>p{margin-left:unset !important}
delfi.ee#$#.article__chunk{margin-left:unset !important}
delfi.ee,epl.ee##.adblock-notice
delfi.ee,~tv.delfi.ee###right
e-autoline.com##OBJECT[width="200"]
e-autoline.com##OBJECT[width="468"]
ehitusfoorum.com##.panel.bg3 > div:nth-child(1) > div:nth-child(2) > center:nth-child(1)
ehuumor.ee###modal
ekspressauto.ee##div[class=banners]
epl.delfi.ee##a[href*="EPL_suur"]
geenius.ee##a[href*="delivery/ck.php"]
hinnavaatlus.ee###rek160
hinnavaatlus.ee###rek728
hinnavaatlus.ee##.banner-single
hinnavaatlus.ee##A[href*="delivery/ck.php"]
hinnavaatlus.ee##div.col-c-1-4
hinnavaatlus.ee##DIV.rek585
hinnavaatlus.ee##DIV.specials
hinnavaatlus.ee##div[id^="ox_"]
hinnavaatlus.ee##script[src*="delivery/fl.js"]
http://*.rr.ru
ilm.ee###taust
ilm.ee##.thisad
ilm.ee#$#.trim > .container{margin-top:0px !important}
kalale.ee##DIV[class$="top-reklaam"]
kalale.ee##DIV[class*="advert-box"]
kalale.ee/upload/images/reklaam/*
kanal2.postimees.ee##.top-space
kanal2.postimees.ee#@#.afs_ads
kanal2.postimees.ee#@#.pub_300x250
kanal2.postimees.ee#@#.pub_300x250m
kanal2.postimees.ee#@#.pub_728x90
kanal2.postimees.ee#@#.text-ad
kanal2.postimees.ee#@#.text-ad-links
kanal2.postimees.ee#@#.text-ads
kanal2.postimees.ee#@#.textAd
kanal2.postimees.ee#@#.text_ad
kanal2.postimees.ee#@#.text_ads
kaup24.ee###titleBannerWidget
kaup24.ee##a[href*="www/delivery/ck.php"]
kaup24.ee##div[id*=idAdbill]
kava.ee###ad_channelgroup
kava.ee###ad_header_1000x120
kava.ee###rightsideBanner
kava.ee##DIV.ad_container
kava.ee##DIV.overlay2
kava.ee##DIV[class*=kava_ad_]
kava.ee##IFRAME[id="frmleftcolads"]
kava.ee##IFRAME[src^="http://www.facebook.com/plugins/login_button.php"]
kava.ee##iframe[src^="https://www.cvkeskus.ee"]
keskus.ee###bannertop
kroonika.ee##div.ads_right_column_adjust
kuldnebors.ee###auto24
kuldnebors.ee##DIV[id*="dBannerLeft"]
kuldnebors.ee##DIV[id*="dBannerTextInPostView"]
kuldnebors.ee##DIV[id*="dBannerTower"]
kuldnebors.ee##DIV[id="dBannerTop"]
kuldnebors.ee##DIV[id^="dBannerPromo"]
kuldnebors.ee##TD[class*="banner_fp_box"]
kuldnebors.ee##TD[class*="banner_mp_box"]
kv.ee###header_banner
kv.ee##DIV.banner_container_1
lounaeestlane.ee###rt-drawer
lounaeestlane.ee##.bannergroup
lounaeestlane.ee/*/banners/*
lpdigileht.epl.ee,ajaleht.ekspress.ee##a[class~=player][href*="reklaam_"]
lpdigileht.epl.ee,ajaleht.ekspress.ee##div[class~=img][style*="reklaam_"]
lpdigileht.epl.ee,ajaleht.ekspress.ee##div[class~=thumb][style*="reklaam_"]
maaleht.ee##DIV.col2
mail.ee###inx-main-roof
mail.ee##tr[id^="row"]
mail.ee/banners/2.0/bx.js*
mallukas.com##aside[class*="widget_image"]
mallukas.com##aside[id^="black-studio-tinymce"]
mallukas.com##div[class*="main-banner"]
mallukas.com##div[class*="useful_banner_manager"]
mallukas.com/reklaamid/*
nagi.ee###banner_top_image
nagi.ee###FooterAds
nagi.ee##DIV.aditem
naistekas.delfi.ee##.banner-slides
nami-nami.ee##a[class=banner-link]
neti.ee###fcadcontainer
neti.ee##.adocean-top
ohtuleht.ee##div.text-banners
ohtuleht.ee##div[id^="banner-adoceanohtuleht"]
okidoki.ee###ad
okidoki.ee###dealsdeals
okidoki.ee###top-smartad
online.ee###topBoxContainer
online.le.ee##a[href*="plugins/adrotate"]
online.le.ee##embed[src*="plugins/adrotate"]
openx.static.kava.ee
optibet.ee###first-page-top-banner-holder
optibet.ee##div[onclick*="promotions"]
pay4results.ee$third-party
perekool.ee###reklaam
perekool.ee##ins[class="bookingaff"]
perekool.ee/pkfiles/adjs.php
piletilevi.ee##.scrollbanners_block
playforia.com##DIV[style*="img/ads"]
pmo.ee/*/banners/*
postimees.ee###gBgAd
postimees.ee###newsletter-form-popup
postimees.ee###sisuturundus
postimees.ee##.allepal-barter
postimees.ee##.articles-recommendations
postimees.ee##.coma-carousel--arco-vara
postimees.ee##.coma-carousel--seb
postimees.ee##.fbLikeBoxOverlay
postimees.ee##.fbOverlay
postimees.ee##.group-topic-with-custom-header--basic-logo-header:has(.group-branding--basic-logo-header-tamrex)
postimees.ee##.group-topic-with-custom-header--kredex
postimees.ee##.group-topic-with-custom-header--reisisoovitus
postimees.ee##.group-topic-with-custom-header--tourest
postimees.ee##.group-topic-with-custom-header--yit
postimees.ee##.header-banner
postimees.ee##.section-branding-container
postimees.ee##.structured-content__group:contains(Sisuturundus)
postimees.ee##.structured-content__group:contains(Teleseriaal «PANK»)
postimees.ee##.structured-content__group:has(.pank-promo-iframe)
postimees.ee##.surprise-container
postimees.ee##aside:contains(Sisuturundus)
postimees.ee##DIV.reisiguruBlockContents
postimees.ee##iframe[src*="cron/ostakvsoov"]
postimees.ee##section.gameFriik
postimees.ee##section[id="customAdProjectBlock"]
postimees.ee#$#.structured-content__group--left{max-width:unset !important}
postimees.ee#$#[itemprop="articleBody"]{max-width:unset !important}
postimees.ee#?#.flex--direction-column.flex.layout--right:-abp-has(> .flex--equal-width.aside--ad)
postimees.ee,rate.ee##DIV.top_banner
rate.ee##DIV.ban_bottom
reporter.postimees.ee##.dfp_ad
rutracker.org###bn-bot-wrap
rutracker.org##.bn-idx
saartehaal.ee##div[class*="wp_bannerize"]
sirp.ee##ul[class="oi-banner__list"]
smsraha.ee###fancybox-container-1
soccernet.ee###adcontainer
soccernet.ee###news_list_banner
soccernet.ee###right_banner
soccernet.ee##div[class*="lb_overlay"]
soccernet.ee##div[class="content-ad"]
soccernet.ee/img/reklaam/*
soov.ee###ap24
static.kava.ee/openx
telegram.ee##.right
toidutare.ee###ads_right_column
toidutare.ee##div.ads_right_column_adjust
toidutare.ee##div.block_custom_wrapper
tv.delfi.ee###banner.left
tv3.ee###ads
tv3.ee##.site-player-blocker.site-player-blocker-adblock.site-player-blocker-active
tv3play.ee##a[onclick*="click_ad_"]
video.reporter.ee/files*.flv?start=0
vorumaateataja.ee###gkBannerTop
vorumaateataja.ee###gkInset > div:first-of-type
vorumaateataja.ee###gkMainbodyBottom > div:first-of-type
vorumaateataja.ee##a[href*="flexbanner"]
vorumaateataja.ee##div[class^="flexbanner"]
whatcar.ee###ad_placeholder
whatcar.ee###big
whatcar.ee/ads/
www.ehitusfoorum.com/bannerid/www/delivery/ajs.php
youtube.com###player-ads
|http://www.auto24.ee/js/Auto24Popup.js
||212.47.219.162/banners
||2mdn.net$third-party
||ad.dumedia.ru$third-party
||ad.mylook.ee$third-party
||adbox.lv$third-party
||adbrite.com$third-party
||adbull.com$third-party
||adbureau.net$third-party
||adclick.co.ee$third-party
||adengage.com$third-party
||adform.net$third-party
||adition.com$third-party
||adkontekst.pl$third-party
||adland.ru$third-party
||adlegend.com$third-party
||admeld.com$third-party
||admin.naistemaailm.ee/upload/images/reklaam/*
||admixer.net$third-party
||admp-tc.delfi.ee
||admulti.com$third-party
||adnet.ee$third-party
||adnetmedia.ee$third-party
||adnxs.com$third-party
||adocean.pl$third-party
||adonspot.com$third-party
||adonweb.ru$third-party
||adreactor.com$third-party
||adriver.ru$third-party
||ads.ee$third-party
||adserver.com$third-party
||adsfac.eu$third-party
||adtaily.pl$third-party
||adtarget.me$third-party
||adtech.de$third-party
||adtechus.com$third-party
||adtegrity.net$third-party
||adultadvertising.net$third-party
||adultfriendfinder.com$third-party
||advertising.aol.com$third-party
||advertising.com$third-party
||advertserve.com$third-party
||afilo.pl$third-party
||afy11.net$third-party
||ahcdns.com$third-party
||aimatch.com$third-party
||ajaleht.ekspress.ee/*/reklaam_*
||am10.ru$third-party
||am11.ru$third-party
||an.yandex.ru/system/context.js
||ap.delfi.ee$third-party
||apex-ad.com$third-party
||aripaev.ee/js/banners.min.js
||atdmt.com$third-party
||axf8.net$third-party
||bannerboxes.com$third-party
||bannerhost.ru$third-party
||bannex.ee$third-party
||bbelements.com$third-party
||begun.ru$third-party
||bepolite.eu$third-party
||bidvertiser.com$third-party
||bizographics.com$third-party
||bkrtx.com$third-party
||blog.tr.ee/banner
||blogads.com$third-party
||bluekai.com$third-party
||bluelithium.com$third-party
||bnrs.ilm.ee
||brazzers.com$third-party
||budsinc.com$third-party
||buduaar.ee/files/Upload/Banners
||buduaar.ee/files/Upload/marketItems
||casalemedia.com$third-party
||chartbeat.com$third-party
||chartbeat.net$third-party
||cherry.ee$third-party
||cherrystatic.net$third-party,domain=~cherry.ee
||cherrystatic.net/banners
||chitika.net$third-party
||city24.ee$third-party,domain=~city24.postimees.ee
||collective-media.com$third-party
||connextra.com$third-party
||contextweb.com$third-party
||cpxinteractive.com$third-party
||crowdscience.com$third-party
||crwdcntrl.net$third-party
||cxense.com$third-party
||dclick.ru$third-party
||delfi.ee/misc/cobancar/*.php
||domdex.com$third-party
||doubleclick.be$third-party
||doubleclick.com$third-party
||doubleclick.de$third-party
||doubleclick.net$third-party
||doublepimp.com$third-party
||dowjoneson.com$third-party
||dt00.net$third-party
||eloqua.com$third-party
||estara.com$third-party
||etology.com$third-party
||extreme-dm.com$third-party
||fastclick.net$third-party
||fastonlineusers.com$third-party
||fortumo.ee$third-party
||freeze.com$third-party
||fwmrm.net$third-party,domain=~tv3play.ee|~tv3.ee
||gemius.pl$third-party
||getclicky.com$third-party
||googleadservices.com$third-party
||googlesyndication.com$third-party
||harrenmedianetwork.com$third-party
||hbmediapro.com$third-party
||hitbox.com$third-party
||hitfarm.com$third-party
||ilm24.ee/uus/ban/
||img.auto24.ee/banners/ox/*
||imgsrv.kuldnebors.ee/banners/$image
||imgsrv.kuldnebors.ee/static/banners/$image
||imlive.com$third-party
||impartner.lt$third-party
||invitemedia.com$third-party
||ixnp.com$third-party
||kalale.ee/media/b2nnerid
||klikivabrik.ee$third-party
||klikki.com$third-party
||kqzyfj.com$third-party
||laanlane.ee/reklaam*
||lekane.net$third-party
||lpdigileht.epl.ee/*/reklaam_*
||luxup.ru$third-party
||magnetic.is$third-party
||marketgid.com$third-party
||maxtraffic.com$third-party
||maxtraffic.eu$third-party
||mediaindex.ee$third-party
||mediaplex.com$third-party
||metaffiliation.com$third-party
||msads.net$third-party
||neoffic.com$third-party
||netaffiliation.com$third-party
||neti.ee/reklaam
||netsales.pl$third-party
||newrelic.com$third-party
||novem.pl$third-party
||olark.com$third-party
||onthe.io$third-party
||openx.org$third-party
||overture.com$third-party
||oxado.com$third-party
||pakkumised.ee$third-party
||pardot.com$third-party
||passion.com$third-party
||pcads.ru$third-party
||perefoorum.ee/banner
||perekool.ee/banners
||pheedo.com$third-party
||pop6.com$third-party
||pro-9.com$third-party
||pro-market.net$third-party
||realmedia.com$third-party
||reklaam.kava.ee
||reklaam.keskus.ee$third-party
||reklaam.nagi.ee$third-party
||reklaam.naistemaailm.ee
||relevant.fi$third-party
||rmxads.com$third-party
||roiservice.com$third-party
||scorecardresearch.com$third-party
||searchco.com$third-party
||serving-sys.com$third-party
||sexinyourcity.com$third-party
||smartad.ee$third-party
||smartadserver.com$third-party
||sn00.net$third-party
||specificclick.net$third-party
||spring-tns.net$third-party
||spylog.com$third-party
||spylog.ru$third-party
||starwave.com$third-party
||static.chilli.ee$third-party
||statistik-gallup.net$third-party
||streamray.com$third-party
||sweetmedia.org$third-party
||tacoda.net$third-party
||teasernet.com$third-party
||textads.ee$third-party
||tns-counter.ru$third-party
||toidutare.ee/img/ads
||traceworks.com$third-party
||trackalyzer.com$third-party
||tradedoubler.com$third-party
||trafficjunky.net$third-party
||tribalfusion.com$third-party
||trigger.ee$third-party
||ui-portal.de^$third-party,domain=~mail.com|~gmx.com
||uimserv.net$third-party
||underclick.ru$third-party
||v.postimees.ee/proxy-ads/*
||ventivmedia.com$third-party
||viglink.com$third-party
||way2traffic.com$third-party
||webtrendslive.com$third-party
||wsod.com$third-party
||www.postimees.ee/newsletter/block
||xgraph.net$third-party
||xiti.com$third-party
||xtendmedia.com$third-party
||yadro.ru$third-party
||yceml.net$third-party
||yieldmanager.com$third-party
||ytsa.net$third-party
||yyr.ee/images/banners
||zangocash.com$third-party
||zanox-affiliate.de$third-party
||zedo.com$third-party
||ztod.com$third-party
~hotelliveeb.ee##iframe[src*="hotelliveeb.ee"]
~postimees.ee##.article-share
~postimees.ee##.article-share__item